### ISSUE TITLE
Class diagram

### ISSUE THREAD

**Issue by zcl190002** [zcl190002/3354-Group1#3]

**Comment by omarhilweh** [comment]
![ClassDiagram2](https://github.com/user-attachments/assets/3a7c6dfe-4688-44ca-a8ef-85b1c6a2908a)

[ClassDiagram.pdf](https://github.com/user-attachments/files/17264824/ClassDiagram.pdf)

**Comment by omarhilweh** [comment]
![3354ClassDiagram drawio (2)](https://github.com/user-attachments/assets/0a603e96-0a25-4e49-ac6e-53d6e78518cd)

**Comment by zcl190002** [comment]
Looks good.
